import { DisplayHeading, EditorialHeading, PageContainer, Section, SectionLabel } from "@/components/primitives/Editorial";
import { RichTextCopy, RichTextInline } from "@/components/primitives/RichText";
import type { Locale } from "@/content/locales";
import { getRunningContent, type RunningBlock, type RunningMedia } from "@/content/running";
import type { RichText } from "@/content/rich-text";
import styles from "./RunningProject.module.css";

function NarrativeSection({ content, id, tone }: { content: RunningBlock; id: string; tone?: "darkMatter" | "running" }) {
  if (!content.isVisible) return null;
  return <Section tone={tone} className={styles.bordered} aria-labelledby={id}><PageContainer><div className={styles.stack}><SectionLabel>{content.label}</SectionLabel><DisplayHeading as="h2" id={id} className={styles.sectionHeading}><RichTextInline value={content.heading} /></DisplayHeading><RichTextCopy value={content.body} /></div></PageContainer></Section>;
}

function RunnerStudy({ text, media }: { text: { title: RichText; label: string; body: RichText }; media: RunningMedia[] }) {
  return <><figure className={styles.study}><figcaption><strong><RichTextInline value={text.title} /></strong><span>{text.label}</span></figcaption><div className={styles.telemetry} aria-hidden="true"><div className={styles.graph}>{Array.from({ length: 10 }, (_, index) => <i key={index} />)}<b /></div><div className={styles.runner}><span className={styles.head} /><span className={styles.torso} /><span className={styles.armOne} /><span className={styles.armTwo} /><span className={styles.legOne} /><span className={styles.legTwo} /></div><div className={styles.scale}><span>easy</span><span>hard</span></div></div><RichTextCopy value={text.body} /></figure>{media.map((item) => <figure className={styles.media} key={item.src}><img src={item.src} alt={item.alt} />{item.caption && <figcaption>{item.caption}</figcaption>}</figure>)}</>;
}

export function RunningProject({ locale }: { locale: Locale }) {
  const content = getRunningContent(locale);
  return <><Section className={styles.hero} aria-labelledby="running-heading"><PageContainer><div className={styles.heroStack}><SectionLabel>{content.hero.label}</SectionLabel><DisplayHeading id="running-heading"><RichTextInline value={content.hero.heading} /></DisplayHeading><RichTextCopy value={content.hero.intro} /></div></PageContainer></Section><NarrativeSection content={content.problem} id="problem-heading" /><NarrativeSection content={content.restraint} id="restraint-heading" tone="darkMatter" /><Section className={styles.bordered} aria-labelledby="principles-heading"><PageContainer><div className={styles.stack}><SectionLabel>{content.principles.label}</SectionLabel><DisplayHeading as="h2" id="principles-heading" className={styles.sectionHeading}><RichTextInline value={content.principles.heading} /></DisplayHeading><ol className={styles.principles}>{content.principles.items.map((principle) => <li key={principle.order}><span>{String(principle.order).padStart(2, "0")}</span><EditorialHeading><RichTextInline value={principle.text} /></EditorialHeading></li>)}</ol></div></PageContainer></Section>{content.object.isVisible && <Section tone="running" aria-labelledby="object-heading"><PageContainer><div className={styles.stack}><SectionLabel>{content.object.label}</SectionLabel><DisplayHeading as="h2" id="object-heading" className={styles.sectionHeading}><RichTextInline value={content.object.heading} /></DisplayHeading><RichTextCopy value={content.object.body} /><RunnerStudy text={content.object.study} media={content.object.media} /></div></PageContainer></Section>}<NarrativeSection content={content.build} id="build-heading" /><NarrativeSection content={content.state} id="state-heading" />{content.liveApp.isVisible && <Section className={styles.playSection}><PageContainer><a className={styles.playLink} href={content.liveApp.href} target="_blank" rel="noopener noreferrer">{content.liveApp.label}</a></PageContainer></Section>}</>;
}
